blank_issues_enabled: false
contact_links:
  - name: Contact us
    url: https://tenzir.com/contact
    about: Reach out to Tenzir
  - name: Chat
    url: https://tenzir.riot.im
    about: Come chat with us interactively
